[project]
name = "agentica-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
]

[dependency-groups]
dev = [
    "pyright>=1.1.399",
]
