name: ci
on:
  push:
  pull_request:


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - uses: pnpm/action-setup@v4
      - run: pnpm lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm build


